sudo: false

language: node_js
node_js: '8'

cache:
  directories:
    - ~/.npm

notifications:
  email: false

before_install:
  - yarn add -D coveralls

scripts:
  - yarn test

after_success:
  - COVERALLS_REPO_TOKEN=$coverall_token yarn test:coverage:coveralls && rm -rf ./coverage
  - yarn travis-deploy-once --pro "yarn semantic-release"

branches:
  only: master
